GET http://localhost:3000/users

###
# API Call to create User
POST http://localhost:3000/register 
Content-Type: application/json

{
    "name": "Vikas", 
    "username" : "vikaskaly@gmail.com" ,
    "password": "password"

}

###
# API call to try to login
POST http://localhost:3000/login 
Content-Type: application/json

{
    "name": "Vikas", 
    "username" : "vikaskaly@gmail.com",
    "password": "password"

}
